/**
 * Synthetic Test Fixtures matching ASTRA-DC-v0.1 contracts
 */

import type {
  ChangeDetectionResult,
  ChangeRegion,
  InvestigationDossier,
  ScenePair,
  TemporalEvidenceNode,
  TemporalSeries,
} from "../types/api";

export const MOCK_TEMPORAL_SERIES: TemporalSeries = {
  series_id: "series_grid_lon77.33_lat13.08_c0000_r0000_z14",
  grid_cell_id: "grid_lon77.33_lat13.08_c0000_r0000_z14",
  tile_col: 0,
  tile_row: 0,
  zoom_level: 14,
  observation_count: 4,
  start_time: "2026-01-15T10:30:00Z",
  end_time: "2026-04-15T10:30:00Z",
  timespan_days: 90.0,
  observations: [
    {
      observation_id: "obs_tile_c0000_r0000_z14_01",
      scene_id: "demo_synthetic_scene_20260115",
      tile_id: "tile_c0000_r0000_z14_01",
      acquisition_time: "2026-01-15T10:30:00Z",
      sensor: "MSI",
      platform: "Sentinel-2A",
      crs: "EPSG:32643",
      bounds_wgs84: { min_lon: 77.33, min_lat: 13.08, max_lon: 77.35, max_lat: 13.10 },
      spatial_resolution_m: 10.0,
      cloud_cover_percentage: 0.0,
      bands: ["B02", "B03", "B04", "B08"],
      file_path: "data/processed/tiles/obs_01.tif",
      is_synthetic: true,
    },
    {
      observation_id: "obs_tile_c0000_r0000_z14_02",
      scene_id: "demo_synthetic_scene_20260215",
      tile_id: "tile_c0000_r0000_z14_02",
      acquisition_time: "2026-02-15T10:30:00Z",
      sensor: "MSI",
      platform: "Sentinel-2B",
      crs: "EPSG:32643",
      bounds_wgs84: { min_lon: 77.33, min_lat: 13.08, max_lon: 77.35, max_lat: 13.10 },
      spatial_resolution_m: 10.0,
      cloud_cover_percentage: 0.0,
      bands: ["B02", "B03", "B04", "B08"],
      file_path: "data/processed/tiles/obs_02.tif",
      is_synthetic: true,
    },
  ],
};

export const MOCK_SCENE_PAIR: ScenePair = {
  pair_id: "pair_obs_01__obs_02",
  earlier_observation: MOCK_TEMPORAL_SERIES.observations[0],
  later_observation: MOCK_TEMPORAL_SERIES.observations[1],
  compatibility: {
    is_compatible: true,
    crs_match: true,
    gsd_match: true,
    footprint_overlap_ratio: 1.0,
    temporal_baseline_days: 31.0,
    rejection_reasons: [],
  },
  pairing_method: "baseline_t0",
};

export const MOCK_CHANGE_REGION: ChangeRegion = {
  region_id: "reg_0002",
  pixel_count: 900,
  area_px: 900,
  area_m2: 90000.0,
  bbox_px: [200, 200, 230, 230],
  bbox_wgs84: { min_lon: 77.335, min_lat: 13.085, max_lon: 77.345, max_lat: 13.095 },
  centroid_px: [215.0, 215.0],
  centroid_wgs84: [77.340, 13.090],
  mean_change_score: 0.825,
  max_change_score: 0.945,
};

export const MOCK_CHANGE_DETECTION_RESULT: ChangeDetectionResult = {
  result_id: "cdr_pair_obs_01__obs_02",
  scene_pair_id: "pair_obs_01__obs_02",
  earlier_tile_id: "tile_c0000_r0000_z14_01",
  later_tile_id: "tile_c0000_r0000_z14_02",
  algorithm_id: "pixel_difference",
  algorithm_version: "1.0.0",
  parameters: { threshold: 0.35 },
  metrics: {
    total_pixels: 262144,
    valid_pixels: 262144,
    invalid_pixels: 0,
    changed_pixels: 1525,
    changed_fraction: 0.0058,
    number_of_regions: 3,
    changed_area_px: 1525,
    changed_area_m2: 152500.0,
    mean_change_score: 0.78,
    max_change_score: 0.95,
    threshold_used: 0.35,
    threshold_method: "otsu",
  },
  regions: [MOCK_CHANGE_REGION],
  created_at: "2026-02-15T10:30:00Z",
  execution_time_ms: 120,
  provenance_id: "prov_cdr_12345678",
  is_synthetic: true,
  is_cached: false,
};

export const MOCK_TIMELINE_NODES: TemporalEvidenceNode[] = [
  {
    observation_id: "obs_tile_01",
    acquisition_time: "2026-01-15T10:30:00Z",
    sensor: "MSI",
    platform: "Sentinel-2A",
    node_status: "PRE_CHANGE_ABSENCE",
    m4d_decision: null,
    heuristic_support_score: 0.0,
    eligible_for_earliest_support: false,
    spatial_correspondence: {
      status: "EXACT_PIXEL_GRID",
      relationship: "MATCHED",
      is_spatially_compatible: true,
      iou_wgs84: 1.0,
      centroid_distance_m: 0.0,
      centroid_distance_px: 0.0,
      crs_match: true,
      gsd_match: true,
    },
    category_observed: null,
    category_confidence: null,
    evidence_score_m4c: null,
    is_cross_sensor: false,
    decision_reasons: ["Pre-change absence confirmed."],
    data_limitations: [],
  },
  {
    observation_id: "obs_tile_02",
    acquisition_time: "2026-02-15T10:30:00Z",
    sensor: "MSI",
    platform: "Sentinel-2B",
    node_status: "EARLIEST_SUPPORTING",
    m4d_decision: "RETAINED",
    heuristic_support_score: 0.92,
    eligible_for_earliest_support: true,
    spatial_correspondence: {
      status: "EXACT_PIXEL_GRID",
      relationship: "MATCHED",
      is_spatially_compatible: true,
      iou_wgs84: 1.0,
      centroid_distance_m: 0.0,
      centroid_distance_px: 0.0,
      crs_match: true,
      gsd_match: true,
    },
    category_observed: "construction",
    category_confidence: "high",
    evidence_score_m4c: 0.95,
    is_cross_sensor: false,
    decision_reasons: ["Earliest supporting observation satisfied RETAINED."],
    data_limitations: [],
  },
  {
    observation_id: "obs_tile_03",
    acquisition_time: "2026-03-15T10:30:00Z",
    sensor: "MSI",
    platform: "Sentinel-2A",
    node_status: "PERSISTENT_SUPPORT",
    m4d_decision: "RETAINED",
    heuristic_support_score: 0.88,
    eligible_for_earliest_support: false,
    spatial_correspondence: {
      status: "GEOREFERENCED_BBOX",
      relationship: "MATCHED",
      is_spatially_compatible: true,
      iou_wgs84: 0.88,
      centroid_distance_m: 4.2,
      centroid_distance_px: 0.42,
      crs_match: true,
      gsd_match: true,
    },
    category_observed: "construction",
    category_confidence: "high",
    evidence_score_m4c: 0.91,
    is_cross_sensor: false,
    decision_reasons: ["Persistent support confirmed."],
    data_limitations: [],
  },
];

export const MOCK_INVESTIGATION_DOSSIER: InvestigationDossier = {
  investigation_id: "inv_8c939ce062ed9b8c",
  request: {
    series_id: "series_grid_lon77.33_lat13.08_c0000_r0000_z14",
    discovery_pair_id: "pair_obs_01__obs_02",
    candidate_region_id: "reg_0002",
    pairing_strategy: "baseline",
    requested_format: "json",
  },
  series_id: "series_grid_lon77.33_lat13.08_c0000_r0000_z14",
  discovery_pair_id: "pair_obs_01__obs_02",
  candidate_region_id: "reg_0002",
  temporal_evidence_id: "tem_7c8d9e0f1a2b3c4d",
  stage_results: [
    {
      stage: "series_resolution",
      status: "COMPLETED",
      artifact_id: "series_grid_lon77.33_lat13.08_c0000_r0000_z14",
      provenance_id: null,
      output_path: null,
      error_message: null,
      details: { observation_count: 4 },
      timestamp: "2026-04-15T10:30:00Z",
    },
    {
      stage: "m4e_temporal_evidence",
      status: "COMPLETED",
      artifact_id: "tem_7c8d9e0f1a2b3c4d",
      provenance_id: "prov_tem_7c8d9e0f1a2b3c4d",
      output_path: "data/processed/temporal_evidence/tem_7c8d9e0f1a2b3c4d/result.json",
      error_message: null,
      details: { status: "STRONG_TEMPORAL_SUPPORT" },
      timestamp: "2026-04-15T10:30:00Z",
    },
  ],
  lineage: {
    scene_pair_ids: ["pair_obs_01__obs_02", "pair_obs_01__obs_03"],
    change_detection_result_ids: ["cdr_pair_obs_01__obs_02", "cdr_pair_obs_01__obs_03"],
    evidence_ids: ["evi_01", "evi_02"],
    classification_ids: ["cls_01", "cls_02"],
    suppression_ids: ["sup_01", "sup_02"],
    temporal_evidence_id: "tem_7c8d9e0f1a2b3c4d",
    upstream_hashes: {
      "data/processed/tiles/obs_01.tif": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      "data/processed/tiles/obs_02.tif": "2c26b46b68ffc68ff99b453c1d30413413422d706483bfa0f98a5e886266e7ae",
    },
    candidate_correspondence: {
      pair_obs_01__obs_02: {
        reference_candidate_id: "reg_0002",
        target_pair_id: "pair_obs_01__obs_02",
        status: "EXACT_REFERENCE",
        relationship: "MATCHED",
        matched_region_id: "reg_0002",
        metric_iou: 1.0,
        centroid_distance_m: 0.0,
        candidate_scores: { reg_0002: 1.0 },
        resolution_notes: ["Discovery reference."],
      },
      pair_obs_01__obs_03: {
        reference_candidate_id: "reg_0002",
        target_pair_id: "pair_obs_01__obs_03",
        status: "GEOREFERENCED_BBOX",
        relationship: "MATCHED",
        matched_region_id: "reg_0001",
        metric_iou: 0.88,
        centroid_distance_m: 4.2,
        candidate_scores: { reg_0001: 0.88 },
        resolution_notes: ["Matched reg_0001."],
      },
    },
  },
  provenance_id: "prov_inv_8c939ce062ed9b8c",
  created_at: "2026-04-15T10:30:00Z",
  content_hash: "8c939ce062ed9b8c",
  temporal_evidence: {
    temporal_evidence_id: "tem_7c8d9e0f1a2b3c4d",
    candidate_ref: {
      change_detection_result_id: "cdr_pair_obs_01__obs_02",
      scene_pair_id: "pair_obs_01__obs_02",
      region_id: "reg_0002",
    },
    series_id: "series_grid_lon77.33_lat13.08_c0000_r0000_z14",
    evaluator_id: "astra_temporal_evidence_evaluator",
    evaluator_version: "1.0.0",
    config: {
      evaluator_id: "astra_temporal_evidence_evaluator",
      evaluator_version: "1.0.0",
      min_persistent_observations: 2,
      min_support_score_threshold: 0.45,
      min_bbox_iou_threshold: 0.30,
      max_centroid_distance_m: 60.0,
      max_pre_change_cloud_fraction: 0.1,
      min_pre_change_valid_pixel_ratio: 0.9,
      max_temporal_gap_days: 90.0,
    },
    temporal_support_status: "STRONG_TEMPORAL_SUPPORT",
    confidence_tier: "high",
    onset_estimate: {
      pre_change_observation_id: "obs_tile_01",
      pre_change_date: "2026-01-15T10:30:00Z",
      earliest_support_observation_id: "obs_tile_02",
      earliest_support_date: "2026-02-15T10:30:00Z",
      interval_days: 31.0,
      interval_type: "BOUNDED_HALF_OPEN",
      display_bounding_span: "[2026-01-15, 2026-02-15]",
      physical_onset_interval: "(2026-01-15, 2026-02-15]",
      interval_limitation: "Interval represents discrete satellite sampling bounds.",
    },
    category_evolution: {
      primary_category: "construction",
      evolution_trajectory: ["construction", "construction"],
      is_evolution_valid: true,
      is_conflicted: false,
      audit_notes: [],
    },
    metrics: {
      total_observations_in_series: 4,
      evaluated_nodes_count: 3,
      supporting_nodes_count: 2,
      flagged_nodes_count: 0,
      suppressed_nodes_count: 0,
      absence_nodes_count: 1,
      insufficient_data_nodes_count: 0,
      simultaneous_nodes_count: 0,
      cross_sensor_nodes_count: 0,
    },
    timeline_nodes: MOCK_TIMELINE_NODES,
    decision_reasons: [
      "Earliest supporting observation established at 2026-02-15T10:30:00Z.",
      "Persistent support confirmed across 2 observations.",
    ],
    evidence_limitations: ["Discrete satellite sampling bounds."],
    discovery_scene_pair_id: "pair_obs_01__obs_02",
    evaluated_scene_pair_ids: ["pair_obs_01__obs_02", "pair_obs_01__obs_03"],
    evaluated_change_detection_result_ids: ["cdr_pair_obs_01__obs_02"],
    evaluated_evidence_ids: ["evi_01"],
    evaluated_classification_ids: ["cls_01"],
    upstream_suppression_ids: ["sup_01"],
    upstream_hashes: {},
    provenance_id: "prov_tem_7c8d9e0f1a2b3c4d",
    created_at: "2026-04-15T10:30:00Z",
  },
  status: "COMPLETED",
};
