import type { InvestigationDossier, TemporalEvidenceNode } from "../types/api";

export const DEMO_TIMELINE_NODES: TemporalEvidenceNode[] = [
  {
    observation_id: "obs_tile_c0000_r0000_z14_01",
    acquisition_time: "2026-01-15T10:30:00Z",
    sensor: "MSI",
    platform: "Sentinel-2A",
    node_status: "PRE_CHANGE_ABSENCE",
    m4d_decision: null,
    heuristic_support_score: 0.0,
    eligible_for_earliest_support: false,
    spatial_correspondence: {
      status: "EXACT_PIXEL_GRID",
      relationship: "MATCHED",
      is_spatially_compatible: true,
      iou_wgs84: 1.0,
      centroid_distance_m: 0.0,
      centroid_distance_px: 0.0,
      crs_match: true,
      gsd_match: true,
    },
    category_observed: null,
    category_confidence: null,
    evidence_score_m4c: null,
    is_cross_sensor: false,
    decision_reasons: ["Pre-change absence confirmed in baseline observation."],
    data_limitations: [],
  },
  {
    observation_id: "obs_tile_c0000_r0000_z14_02",
    acquisition_time: "2026-02-15T10:30:00Z",
    sensor: "MSI",
    platform: "Sentinel-2B",
    node_status: "EARLIEST_SUPPORTING",
    m4d_decision: "RETAINED",
    heuristic_support_score: 0.92,
    eligible_for_earliest_support: true,
    spatial_correspondence: {
      status: "EXACT_PIXEL_GRID",
      relationship: "MATCHED",
      is_spatially_compatible: true,
      iou_wgs84: 1.0,
      centroid_distance_m: 0.0,
      centroid_distance_px: 0.0,
      crs_match: true,
      gsd_match: true,
    },
    category_observed: "construction",
    category_confidence: "high",
    evidence_score_m4c: 0.95,
    is_cross_sensor: false,
    decision_reasons: ["Earliest supporting observation satisfied RETAINED."],
    data_limitations: [],
  },
  {
    observation_id: "obs_tile_c0000_r0000_z14_03",
    acquisition_time: "2026-03-15T10:30:00Z",
    sensor: "MSI",
    platform: "Sentinel-2A",
    node_status: "PERSISTENT_SUPPORT",
    m4d_decision: "RETAINED",
    heuristic_support_score: 0.88,
    eligible_for_earliest_support: false,
    spatial_correspondence: {
      status: "GEOREFERENCED_BBOX",
      relationship: "MATCHED",
      is_spatially_compatible: true,
      iou_wgs84: 0.88,
      centroid_distance_m: 4.2,
      centroid_distance_px: 0.42,
      crs_match: true,
      gsd_match: true,
    },
    category_observed: "construction",
    category_confidence: "high",
    evidence_score_m4c: 0.91,
    is_cross_sensor: false,
    decision_reasons: ["Persistent support confirmed across multiple epochs."],
    data_limitations: [],
  },
  {
    observation_id: "obs_tile_c0000_r0000_z14_04",
    acquisition_time: "2026-04-15T10:30:00Z",
    sensor: "MSI",
    platform: "Sentinel-2B",
    node_status: "PERSISTENT_SUPPORT",
    m4d_decision: "RETAINED",
    heuristic_support_score: 0.89,
    eligible_for_earliest_support: false,
    spatial_correspondence: {
      status: "GEOREFERENCED_BBOX",
      relationship: "MATCHED",
      is_spatially_compatible: true,
      iou_wgs84: 0.85,
      centroid_distance_m: 4.5,
      centroid_distance_px: 0.45,
      crs_match: true,
      gsd_match: true,
    },
    category_observed: "construction",
    category_confidence: "high",
    evidence_score_m4c: 0.89,
    is_cross_sensor: false,
    decision_reasons: ["Persistent support re-confirmed in latest epoch."],
    data_limitations: [],
  },
];

export const DEMO_INVESTIGATION_DOSSIER: InvestigationDossier = {
  investigation_id: "inv_8c939ce062ed9b8c",
  request: {
    series_id: "series_grid_lon77.33_lat13.08_c0000_r0000_z14",
    discovery_pair_id: "pair_obs_01__obs_02",
    candidate_region_id: "reg_0002",
    pairing_strategy: "baseline",
    requested_format: "json",
  },
  series_id: "series_grid_lon77.33_lat13.08_c0000_r0000_z14",
  discovery_pair_id: "pair_obs_01__obs_02",
  candidate_region_id: "reg_0002",
  temporal_evidence_id: "tem_7c8d9e0f1a2b3c4d",
  stage_results: [
    {
      stage: "series_resolution",
      status: "COMPLETED",
      artifact_id: "series_grid_lon77.33_lat13.08_c0000_r0000_z14",
      provenance_id: null,
      output_path: null,
      error_message: null,
      details: { observation_count: 4 },
      timestamp: "2026-04-15T10:30:00Z",
    },
    {
      stage: "m4b_change_detection",
      status: "COMPLETED",
      artifact_id: "cdr_pair_obs_01__obs_02",
      provenance_id: "prov_cdr_pair_obs_01__obs_02",
      output_path: "data/processed/change/cdr_pair_obs_01__obs_02.json",
      error_message: null,
      details: {
        number_of_regions: 3,
        changed_pixels: 1525,
        target_region: {
          region_id: "reg_0002",
          pixel_count: 900,
          area_px: 900,
          area_m2: 90000.0,
          bbox_px: [200, 200, 230, 230],
          bbox_wgs84: {
            min_lon: 77.335,
            min_lat: 13.085,
            max_lon: 77.345,
            max_lat: 13.095,
          },
          centroid_px: [215.0, 215.0],
          centroid_wgs84: [77.34, 13.09],
          features: {
            area: 90000.0,
            width_px: 30,
            height_px: 30,
            aspect_ratio: 1.0,
            perimeter_px: 120.0,
            compactness: 0.785,
            rectangularity: 1.0,
            elongation: 1.0,
            orientation_deg: 0.0,
            centroid: [215.0, 215.0],
            boundary_distance_px: 200.0,
            region_density: 1.0,
            fragmentation: 0.0,
          },
        },
      },
      timestamp: "2026-04-15T10:30:01Z",
    },
    {
      stage: "m4c_evidence_extraction",
      status: "COMPLETED",
      artifact_id: "evi_pair_obs_01__obs_02",
      provenance_id: "prov_evi_pair_obs_01__obs_02",
      output_path: null,
      error_message: null,
      details: {
        feature_dimensions: 64,
        target_evidence: {
          region_id: "reg_0002",
          spatial: {
            area_px: 900,
            pixel_count: 900,
            width_px: 30,
            height_px: 30,
            aspect_ratio: 1.0,
            perimeter_px: 120.0,
            compactness: 0.785,
            rectangularity: 1.0,
            elongation: 1.0,
            major_axis_length: 30.0,
            minor_axis_length: 30.0,
            axis_ratio: 1.0,
            linearity_score: 0.0,
            orientation_degrees: 0.0,
            component_density: 1.0,
            shape_regularity: 0.88,
            fragmentation: 0.0,
            distance_to_boundary_px: 200.0,
            neighboring_changed_regions_count: 2,
            area_m2: 90000.0,
          },
          spectral: {
            available: true,
            has_wavelength_metadata: true,
            band_names: ["B02_blue", "B03_green", "B04_red", "B08_nir"],
            earlier_mean_per_band: { B02_blue: 0.12, B03_green: 0.15, B04_red: 0.14, B08_nir: 0.38 },
            later_mean_per_band: { B02_blue: 0.22, B03_green: 0.24, B04_red: 0.25, B08_nir: 0.28 },
            delta_per_band: { B02_blue: 0.1, B03_green: 0.09, B04_red: 0.11, B08_nir: -0.1 },
            brightness_delta: {
              feature_id: "feat_reg_0002_brightness_delta",
              feature_name: "brightness_delta",
              value: 0.1,
              available: true,
              source: "spectral",
            },
            ndvi_mean: {
              feature_id: "feat_reg_0002_ndvi_mean",
              feature_name: "ndvi_mean",
              value: 0.05,
              available: true,
              source: "spectral",
            },
            ndwi_mean: {
              feature_id: "feat_reg_0002_ndwi_mean",
              feature_name: "ndwi_mean",
              value: -0.22,
              available: true,
              source: "spectral",
            },
            water_spectral_criterion_fraction: {
              feature_id: "feat_reg_0002_water_fraction",
              feature_name: "water_fraction",
              value: 0.0,
              available: true,
              source: "spectral",
            },
          },
          context: {
            available: true,
            neighborhood_buffer_px: 15,
            surrounding_mean_change: 0.08,
            region_to_background_contrast: 0.34,
          },
        },
      },
      timestamp: "2026-04-15T10:30:02Z",
    },
    {
      stage: "m4c_classification",
      status: "COMPLETED",
      artifact_id: "cls_pair_obs_01__obs_02",
      provenance_id: "prov_cls_pair_obs_01__obs_02",
      output_path: null,
      error_message: null,
      details: {
        primary_category: "construction",
        confidence: 0.95,
        target_classification: {
          region_id: "reg_0002",
          category: "construction",
          evidence_score: 0.95,
          confidence_tier: "high",
          decision_reason:
            "High geometric rectangularity (1.00) and strong positive brightness delta (+0.10) with marked background contrast (0.34) satisfy construction criteria.",
          is_ambiguous: false,
          conflicting_categories: [],
          candidate_scores: {
            construction: 0.95,
            clearance: 0.32,
            road_development: 0.15,
            water_extent_change: 0.0,
          },
          rule_evaluations: [
            {
              rule_id: "rule_const_geom_rectangularity",
              category: "construction",
              matched: true,
              weight: 30,
              score_contribution: 0.3,
              description: "Bounding box rectangular fill >= 0.60 (observed: 1.00)",
              evidence_used: { rectangularity: 1.0, threshold: 0.6 },
            },
            {
              rule_id: "rule_const_geom_compactness",
              category: "construction",
              matched: true,
              weight: 15,
              score_contribution: 0.15,
              description: "Shape compactness >= 0.20 (observed: 0.785)",
              evidence_used: { compactness: 0.785, threshold: 0.2 },
            },
            {
              rule_id: "rule_const_geom_non_linear",
              category: "construction",
              matched: true,
              weight: 15,
              score_contribution: 0.15,
              description: "Linearity <= 0.65 and aspect ratio <= 4.0 (observed: 0.00, 1.00)",
              evidence_used: { linearity: 0.0, aspect_ratio: 1.0 },
            },
            {
              rule_id: "rule_const_spec_brightness_increase",
              category: "construction",
              matched: true,
              weight: 25,
              score_contribution: 0.25,
              description: "Spectral brightness delta > 0.05 (observed: +0.10)",
              evidence_used: { brightness_delta: 0.1, threshold: 0.05 },
            },
            {
              rule_id: "rule_const_ctx_contrast",
              category: "construction",
              matched: true,
              weight: 15,
              score_contribution: 0.15,
              description: "Region to background contrast >= 0.15 (observed: 0.34)",
              evidence_used: { contrast: 0.34, threshold: 0.15 },
            },
            {
              rule_id: "disqual_const_water_presence",
              category: "construction",
              matched: false,
              weight: 50,
              score_contribution: 0.0,
              description: "Water criterion fraction > 0.30 disqualifier (observed: 0.00)",
              evidence_used: { water_fraction: 0.0 },
            },
            {
              rule_id: "disqual_const_extreme_elongation",
              category: "construction",
              matched: false,
              weight: 40,
              score_contribution: 0.0,
              description: "Linearity > 0.85 and aspect ratio > 6.0 disqualifier (observed: 0.00, 1.00)",
              evidence_used: { linearity: 0.0, aspect_ratio: 1.0 },
            },
          ],
        },
      },
      timestamp: "2026-04-15T10:30:03Z",
    },
    {
      stage: "m4d_suppression",
      status: "COMPLETED",
      artifact_id: "sup_pair_obs_01__obs_02",
      provenance_id: "prov_sup_pair_obs_01__obs_02",
      output_path: "data/processed/suppression/sup_pair_obs_01__obs_02_mask.tif",
      error_message: null,
      details: {
        outcome: "PASS",
        retained_count: 2,
        target_suppression: {
          region_id: "reg_0002",
          decision: "retained",
          artifact_risk_score: 0.06,
          artifact_risk_interpretation:
            "Negligible false-alarm risk across atmospheric, geometric, and registration detectors.",
          decision_basis: "CONSERVATIVE_MULTI_EVIDENCE",
          decision_reasons: [
            "Candidate passes all conservative false-alarm gates; no hard suppression condition met.",
            "Composite heuristic risk index F=0.06 is below warning threshold (0.35).",
            "Retained for downstream temporal persistence evaluation (Phase M4E).",
          ],
          primary_attribution: null,
          contributing_artifacts: [],
          hard_triggered: false,
          original_category: "construction",
          retained_category: "construction",
          confidence_tier_adjusted: "high",
          data_limitations: [],
          artifact_evaluations: [
            {
              artifact_type: "cloud_contamination",
              detected: false,
              artifact_score: 0.02,
              weight: 0.25,
              hard_triggered: false,
              description: "Visible reflectance and Cirrus/SWIR absorption rule out cloud contamination.",
              metrics_used: { vis_reflectance: 0.24, cirrus_reflectance: 0.003 },
            },
            {
              artifact_type: "cloud_shadow",
              detected: false,
              artifact_score: 0.0,
              weight: 0.2,
              hard_triggered: false,
              description: "No directional solar ray alignment with any upstream cloud candidate.",
              metrics_used: { solar_azimuth: 145.0, ray_cloud_found: false },
            },
            {
              artifact_type: "coregistration_edge_shear",
              detected: false,
              artifact_score: 0.01,
              weight: 0.2,
              hard_triggered: false,
              description: "Component width 30px exceeds 2.0px edge shear threshold; no dipole reversal.",
              metrics_used: { minor_axis_width_px: 30.0, edge_overlap: 0.05 },
            },
            {
              artifact_type: "snow_ice",
              detected: false,
              artifact_score: 0.0,
              weight: 0.15,
              hard_triggered: false,
              description: "NDSI index (-0.18) well below snow threshold (0.40).",
              metrics_used: { ndsi: -0.18, threshold: 0.4 },
            },
            {
              artifact_type: "viewing_geometry_parallax",
              detected: false,
              artifact_score: 0.03,
              weight: 0.1,
              hard_triggered: false,
              description: "Near-nadir viewing geometry (off-nadir angle < 4°); negligible parallax shift.",
              metrics_used: { off_nadir_angle_deg: 3.2 },
            },
            {
              artifact_type: "global_illumination_drift",
              detected: false,
              artifact_score: 0.0,
              weight: 0.1,
              hard_triggered: false,
              description: "Local contrast 0.34 exceeds 0.15 retention margin; protected from illumination drift.",
              metrics_used: { local_contrast: 0.34, background_median_delta: 0.04 },
            },
            {
              artifact_type: "haze_aerosol",
              detected: false,
              artifact_score: 0.0,
              weight: 0.05,
              hard_triggered: false,
              description: "No diffuse aerosol veil detected across optical channels.",
              metrics_used: { blue_band_scattering: 0.02 },
            },
            {
              artifact_type: "sensor_noise_dropout",
              detected: false,
              artifact_score: 0.0,
              weight: 0.05,
              hard_triggered: false,
              description: "Region area 900px far exceeds 2px salt-and-pepper noise threshold.",
              metrics_used: { area_px: 900 },
            },
            {
              artifact_type: "cross_sensor_limitation",
              detected: false,
              artifact_score: 0.0,
              weight: 0.0,
              hard_triggered: false,
              description: "Homogeneous Sentinel-2 MSI acquisition; no cross-sensor calibration penalty.",
              metrics_used: { sensor_pair: "MSI_MSI" },
            },
          ],
        },
      },
      timestamp: "2026-04-15T10:30:04Z",
    },
    {
      stage: "m4e_temporal_evidence",
      status: "COMPLETED",
      artifact_id: "tem_7c8d9e0f1a2b3c4d",
      provenance_id: "prov_tem_7c8d9e0f1a2b3c4d",
      output_path: "data/processed/temporal_evidence/tem_7c8d9e0f1a2b3c4d/result.json",
      error_message: null,
      details: { status: "STRONG_TEMPORAL_SUPPORT" },
      timestamp: "2026-04-15T10:30:05Z",
    },
  ],
  lineage: {
    scene_pair_ids: ["pair_obs_01__obs_02", "pair_obs_01__obs_03", "pair_obs_01__obs_04"],
    change_detection_result_ids: [
      "cdr_pair_obs_01__obs_02",
      "cdr_pair_obs_01__obs_03",
      "cdr_pair_obs_01__obs_04",
    ],
    evidence_ids: ["evi_01", "evi_02", "evi_03"],
    classification_ids: ["cls_01", "cls_02", "cls_03"],
    suppression_ids: ["sup_01", "sup_02", "sup_03"],
    temporal_evidence_id: "tem_7c8d9e0f1a2b3c4d",
    upstream_hashes: {
      "data/processed/tiles/obs_01.tif": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      "data/processed/tiles/obs_02.tif": "2c26b46b68ffc68ff99b453c1d30413413422d706483bfa0f98a5e886266e7ae",
    },
    candidate_correspondence: {
      pair_obs_01__obs_02: {
        reference_candidate_id: "reg_0002",
        target_pair_id: "pair_obs_01__obs_02",
        status: "EXACT_REFERENCE",
        relationship: "MATCHED",
        matched_region_id: "reg_0002",
        metric_iou: 1.0,
        centroid_distance_m: 0.0,
        candidate_scores: { reg_0002: 1.0 },
        resolution_notes: ["Discovery reference."],
      },
      pair_obs_01__obs_03: {
        reference_candidate_id: "reg_0002",
        target_pair_id: "pair_obs_01__obs_03",
        status: "GEOREFERENCED_BBOX",
        relationship: "MATCHED",
        matched_region_id: "reg_0001",
        metric_iou: 0.88,
        centroid_distance_m: 4.2,
        candidate_scores: { reg_0001: 0.88 },
        resolution_notes: ["Matched reg_0001 via spatial bounding correspondence."],
      },
      pair_obs_01__obs_04: {
        reference_candidate_id: "reg_0002",
        target_pair_id: "pair_obs_01__obs_04",
        status: "GEOREFERENCED_BBOX",
        relationship: "MATCHED",
        matched_region_id: "reg_0003",
        metric_iou: 0.85,
        centroid_distance_m: 4.8,
        candidate_scores: { reg_0003: 0.85 },
        resolution_notes: ["Matched reg_0003 via spatial bounding correspondence."],
      },
    },
  },
  provenance_id: "prov_inv_8c939ce062ed9b8c",
  created_at: "2026-04-15T10:30:05Z",
  content_hash: "8c939ce062ed9b8c",
  temporal_evidence: {
    temporal_evidence_id: "tem_7c8d9e0f1a2b3c4d",
    candidate_ref: {
      change_detection_result_id: "cdr_pair_obs_01__obs_02",
      scene_pair_id: "pair_obs_01__obs_02",
      region_id: "reg_0002",
    },
    series_id: "series_grid_lon77.33_lat13.08_c0000_r0000_z14",
    evaluator_id: "astra_temporal_evidence_evaluator",
    evaluator_version: "1.0.0",
    config: {
      evaluator_id: "astra_temporal_evidence_evaluator",
      evaluator_version: "1.0.0",
      min_persistent_observations: 2,
      min_support_score_threshold: 0.45,
      min_bbox_iou_threshold: 0.30,
      max_centroid_distance_m: 60.0,
      max_pre_change_cloud_fraction: 0.1,
      min_pre_change_valid_pixel_ratio: 0.9,
      max_temporal_gap_days: 90.0,
    },
    temporal_support_status: "STRONG_TEMPORAL_SUPPORT",
    confidence_tier: "high",
    onset_estimate: {
      pre_change_observation_id: "obs_tile_c0000_r0000_z14_01",
      pre_change_date: "2026-01-15T10:30:00Z",
      earliest_support_observation_id: "obs_tile_c0000_r0000_z14_02",
      earliest_support_date: "2026-02-15T10:30:00Z",
      interval_days: 31.0,
      interval_type: "BOUNDED_HALF_OPEN",
      display_bounding_span: "[2026-01-15, 2026-02-15]",
      physical_onset_interval: "(2026-01-15, 2026-02-15]",
      interval_limitation:
        "Interval represents discrete satellite sampling bounds; exact physical date of occurrence is unobservable.",
    },
    category_evolution: {
      primary_category: "construction",
      evolution_trajectory: ["construction", "construction"],
      is_evolution_valid: true,
      is_conflicted: false,
      audit_notes: [],
    },
    metrics: {
      total_observations_in_series: 4,
      evaluated_nodes_count: 4,
      supporting_nodes_count: 3,
      flagged_nodes_count: 0,
      suppressed_nodes_count: 0,
      absence_nodes_count: 1,
      insufficient_data_nodes_count: 0,
      simultaneous_nodes_count: 0,
      cross_sensor_nodes_count: 0,
    },
    timeline_nodes: DEMO_TIMELINE_NODES,
    decision_reasons: [
      "Earliest supporting observation established at 2026-02-15T10:30:00Z.",
      "Persistent support confirmed across 2 consecutive acquisitions.",
    ],
    evidence_limitations: [
      "Interval represents discrete satellite sampling bounds; exact physical date of occurrence is unobservable.",
    ],
    discovery_scene_pair_id: "pair_obs_01__obs_02",
    evaluated_scene_pair_ids: ["pair_obs_01__obs_02", "pair_obs_01__obs_03"],
    evaluated_change_detection_result_ids: ["cdr_pair_obs_01__obs_02"],
    evaluated_evidence_ids: ["evi_01"],
    evaluated_classification_ids: ["cls_01"],
    upstream_suppression_ids: ["sup_01"],
    upstream_hashes: {},
    provenance_id: "prov_tem_7c8d9e0f1a2b3c4d",
    created_at: "2026-04-15T10:30:05Z",
  },
  status: "COMPLETED",
};
